config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: "users#frontpage"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do

    member do "favorites"
      get 'favorites'
    end

    resources :photos do
      resources :comments

      member do
        post 'add_favorite'
        delete 'remove_favorite'
      end

    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  mount_uploader :url, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_filter :configure_permitted_parameters, if: :devise_controller?
  #
  # protected
  # def configure_permitted_parameters
  #    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
  #    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  #    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
  end

  def create
    if !current_user
      flash[:alert] = "Not authorized to create a comment."
    else
      @photo = Photo.find(params[:photo_id])
      @comment = @photo.comments.create(comment_params.merge(user: current_user))
      flash[:notice] = "Comment successfully posted."
    end
    redirect_to request.referrer
  end

  def edit
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      flash[:alert] = "Not authorized to edit comment."
      redirect_to request.referrer
    end
  end

  def update
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      flash[:alert] = "Not authorized to edit this comment."
    else
      @comment.update(comment_params)
    end
    redirect_to user_photo_path(@photo.user, @photo)
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.find(params[:id])
    if @comment.user != current_user
      flash[:alert] = "Not authorized to delete this comment."
    else
      @comment.destroy
      flash[:notice] = "Comment successfully deleted."
    end
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
    if current_user
      @comment = Comment.new
    end
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create
  end

  def create
    @user = User.find(params[:user_id])
    if current_user
      @photo = @user.photos.create(photo_params.merge(user: current_user))
      redirect_to [@user, @photo]
    else
      flash[:alert] = "Not authorized to upload photo."
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])

    if @photo.user == current_user
      @photo.update(photo_params)
    else
      flash[:alert] = "Not authorized to edit this photo."
    end
    redirect_to [@user, @photo]
  end

  def destroy
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])

    if @photo.user == current_user
      @photo.destroy
    else
      flash[:alert] = "Not authorized to delete photo."
    end
    redirect_to @user
  end

  def add_favorite
    @user = current_user
    @photo = Photo.find(params[:id])

    if current_user
      Favorite.create(user: @user, photo: @photo)
      respond_to do |format|
        format.html do
          flash[:notice] = "Photo added to favorites."
          redirect_to request.referrer
        end
        format.js { }
      end
    else
      flash[:alert] = "Not authorized to add favorites."
    end
  end

  def remove_favorite
    @user = current_user
    @photo = Photo.find(params[:id])

    if current_user
      Favorite.find_by(user: @user, photo: @photo).destroy
      respond_to do |format|
        format.html do
          flash[:notice] = "Photo removed from favorites."
          redirect_to request.referrer
        end
        format.js { }
      end
    else
      flash[:alert] = "Not authorized to remove favorites."
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :url)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def frontpage
    @photos = Photo.order("RANDOM()").limit(9)
  end

  def index
    @users = User.all.order("username ASC")
  end

  def show
    @user = User.find(params[:id])
  end

  def favorites
    @user = current_user
    @photos = @user.favorites
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<%= form_for [@user, @photo, @comment] do |f| %>
  <h3><%= f.label "Edit Comment" %></h3>
  <p><%= f.text_field :body, size: "100" %></p>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photos-on-Rails</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <ul>
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Browse", users_path %></li>
        <% if !current_user %>
        <li style="float:right" class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to "Register", new_user_registration_path %></li>
        <li style="float:right" class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to "Login", new_user_session_path %></li>
        <% else %>
        <li class="<%= 'active' if current_page?(current_user) %>"><%= link_to "My Photos", current_user %></li>
        <li class="<%= 'active' if current_page?(favorites_user_path(current_user)) %>"><%= link_to "Favorites", favorites_user_path(current_user) %></li>
        <li style="float:right"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li style="float:right" class="<%= 'active' if current_page?(edit_user_registration_path(current_user)) %>"><%= link_to "Profile", edit_user_registration_path(current_user) %></li>
        <li style="float:right" class="<%= 'active' if current_page?(new_user_photo_path(current_user)) %>"><%= link_to "Upload Photo", new_user_photo_path(current_user) %></li>
        <% end %>
      </ul>
    </div>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="header">
        <div class="header-logo">
          <%= link_to image_tag("logo.png", :class => "header-img"), root_path %>
          <h1><%= link_to "Photos-on-Rails", root_path %></h1>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for [@user, @photo], html: { multipart: true } do |f| %>
  <div class="field">
    <p><%= f.label "Photo Title" %></p>
    <%= f.text_field :title, size: "100" %>
  </div>
  <div class="field">
    <% if f.object.url? %>
      <p><%= f.label "Replace Image" %></p>
    <% else %>
      <p><%= f.label "Add Photo" %></p>
    <% end %>
    <%= f.file_field :url %>

    <div class="actions">
      <p><%= f.submit %></p>
    </div>

    <% if f.object.url? %>
      <%= image_tag f.object.url.url, :class => "full-img" %>
    <% end %>
  </div>

<% end %>

app/views/photos/add_favorite.js.erb
$('a[href*="add_favorite"]').each(function () {
  url = $(this).attr('href').replace('add_favorite', 'remove_favorite')
  $(this).attr('href', url)
  $(this).attr('data-method', 'delete')
})

app/views/photos/edit.html.erb
<h2>Edit Photo</h2>
<%= render 'form', photo: @photo %>

<%= link_to 'Back to Photo', [@photo.user, @photo] %>

app/views/photos/new.html.erb
<h2>Upload Photo</h2>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', :back %>

app/views/photos/remove_favorite.js.erb
$('a[href*="remove_favorite"]').each(function () {
  url = $(this).attr('href').replace('remove_favorite', 'add_favorite')
  $(this).attr('href', url)
  $(this).attr('data-method', 'post')
})

app/views/photos/show.html.erb
<div class="full-title">
  <div class="photo-title"><h3><%= @photo.title %></h3> by <%= link_to @user.username, @user %></div>
  <% if current_user %>
    <% if @photo.users.include? current_user %>
      <%= link_to '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe, remove_favorite_user_photo_path(current_user, @photo), remote: true, id: "favicon", method: :delete, class: "fav", title: "Remove Favorite" %>
    <% else %>
      <%= link_to '<i class="fa fa-star-o" aria-hidden="true"></i>'.html_safe, add_favorite_user_photo_path(current_user, @photo), remote: true, id: "favicon", method: :post, class: "no-fav", title: "Add Favorite" %>
    <% end %>
  <% end %>
  <%= link_to '<i class="fa fa-comments-o" aria-hidden="true"></i>'.html_safe, {anchor: "comments"}, class: "no-fav", title: "View Comments" %>
</div>
<%= image_tag @photo.url, :class => "full-img" %>
<% if @photo.user == current_user %>
<p><%= link_to "Edit Photo", edit_user_photo_path(@user) %> | <%= link_to "Delete Photo", user_photo_path(@user, @photo), method: :delete, data: {confirm: "Are you sure you want to delete this photo?"} %> </p>
<% end %>
<div class="comments-container" id="comments">
  <h3>Comments</h3>
  <% if @photo.comments.length == 0 %>
    <p><strong><i><small>This photo doesn't have any comments yet</small></i></strong></p>
  <% else %>
    <% @photo.comments.each do |comment| %>
      <div class="single-comment">
        <small><strong><%= link_to comment.user.username, comment.user %></strong></small><br>
          <%= comment.body %>
        <% if comment.user == current_user %>
          <small>(<%= link_to "Edit", edit_user_photo_comment_path(@user, @photo, comment) %> | <%= link_to "Delete", user_photo_comment_path(@user, @photo, comment), method: :delete %>)</small>
        <% end %>
      </div>
    <% end %>
    <% end %>
    <% if current_user %>
      <%= form_for [@user, @photo, @comment] do |f| %>
        <small><%= f.label "Post a new Comment" %></small><br>
        <p><%= f.text_field :body, size: "100"  %></p>
        <%= f.submit "Add comment" %>
      <% end %>
    <% end %>
</div>

app/views/users/favorites.html.erb
<div class="user-gallery-title">
  <h3>Favorites for <%= current_user.username %></h3>
</div>
<div class="user-gallery">
  <% if @photos.length == 0 %>
    <p><strong><i><small>Looks like you don't have any favorites yet</small></i></strong></p>
  <% else %>
    <% @photos.each do |photo| %>
    <div class="user-gallery-item">
    <p><%= link_to photo.photo.title, [photo.photo.user, photo.photo] %> by <%= link_to photo.photo.user.username, photo.photo.user %></p>
    <%= link_to image_tag(photo.photo.url, :class => "user-gallery-img"), [photo.photo.user, photo.photo]  %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/users/frontpage.html.erb
<div class="index-gallery">
<% @photos.each do |p| %>
  <div class="index-gallery-img" style='background-image: url("<%= p.url %>")'><%= link_to ' ', [p.user, p] %></div>
<% end %>
</div>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <% if u.photos.length >= 3 %>
    <div class="user-index-title"><h3>Photos by <%= link_to u.username, u %></h3></div>
    <div class="index-gallery">
    <% u.photos.take(3).each do |p| %>
      <div class="index-gallery-img" style='background-image: url("<%= p.url %>")'><%= link_to ' ', [u, p] %></div>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="user-gallery-title">
  <h3><%= @user.username %>'s photos</h3>
</div>
<div class="user-gallery">
  <% @user.photos.each do |photo| %>
  <div class="user-gallery-item">
  <p><%= link_to photo.title, [@user, photo] %></p>
  <div class="user-gallery-img" style='background-image: url("<%= photo.url %>")'><%= link_to ' ', [@user, photo] %></div>
  </div>
  <% end %>
</div>